# Generated by Django 2.2.5 on 2019-10-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='province',
            new_name='province_id',
        ),
    ]
