# Generated by Django 2.2.5 on 2019-10-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191020_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='province_id',
            new_name='province',
        ),
    ]
